# This is a config for E2B sandbox template.
# You can use template ID (xc32od6xpln3it81r9iw) or template name (vibe-nextjs-test-tomas-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-tomas-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-tomas-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-tomas-2')

team_id = "01c34bcf-c608-4755-88f9-3a6a21a25fb0"
start_cmd = "./compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-tomas-2"
template_id = "xc32od6xpln3it81r9iw"
